V1.1.9
livingcomputermuseum/Darkstar pull request #11
Opened 2020-12-19 19:40 UTC by devhawala

This pull-request contains several improvements and changes to Darkstar 1.1.0.0 collected over time.
- The commit message to the first commit in branch v1.1.9 contains a list of the code changes, most important are improvements to the network interface and the ability to boot the guest system from the command line through the configuration file, both on Windows and Unixoids.
- The readme files were updated accordingly.
- The version number 1.1.9.0 was chosen only to keep the version in the forked repository out of the way from possibly new versions in the original repo. So feel free to use a differing version matching the main versioning sequence for Darkstar.
- Finally a disk image for StarOS 5.0 was added, with a matching configuration file; this is also an example for a Darkstar configuration file having all parameters with some comments.

2020-12-22 04:55 UTC, jdersch commented on D/Display/DisplayController.cs
> +                    int patternByte = (effectiveScanline & 0x2) == 2 ? _displayBorder & 0xff : _displayBorder >> 8;
The bug here is more subtle -- changing this here provides the correct pattern alignment for Viewpoint, but breaks the pattern on Interlisp-D.  (Currently Interlisp-D looks fine, VP is broken).  Prefer not changing this now until the root cause can be determined.

2020-12-22 04:58 UTC, livingcomputermuseum commented on D/Darkstar.csproj
> +  </PropertyGroup>
Please remove these extraneous changes to the project

2020-12-22 05:02 UTC, livingcomputermuseum commented on D/Display/DisplayController.cs
> +                    int patternByte = (effectiveScanline & 0x2) == 2 ? _displayBorder & 0xff : _displayBorder >> 8;
The root cause of this issue is more subtle.  Without this change, Interlisp-D's border pattern aligns properly and Viewpoint is misaligned; with this change the opposite will be true.  I suspect the root cause is a timing issue during the start of the frame that I have to dig into.  I'd prefer not to change this right now.  (See also line 216.)

2020-12-22 05:02 UTC, livingcomputermuseum commented on D/Ethernet/EthernetController.cs
> +                //(debug) Console.WriteLine("Pending buffer full; dropping this packet.");
Please remove commented out debug lines.

2020-12-22 05:04 UTC, livingcomputermuseum commented on D/Ethernet/EthernetController.cs
> +                    _inputPacket.Enqueue((ushort)0);
Are you certain the microcode expects this and that there isn't a different root cause of this issue?  The Ethernet code as it stands works fine under Interlisp-D (tested with the TCP/IP stack) and as far as I know the Ethernet microcode between Interlisp and VP is basically identical.

2020-12-22 05:07 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +			this.localAddress = Configuration.HostID;
Un-tabify this file, please (4 spaces per tab).

2020-12-22 05:08 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        void IPacketInterface.RegisterReceiveCallback(ReceivePacketDelegate callback) {
Fix brace style (here and elsewhere in this file.)

2020-12-22 05:08 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +            //(debug) Console.Write("** sending packed, len = {0} bytes\n", byteLen);
Please remove this line (or make it a Log.Write call.)

2020-12-22 05:08 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        	//(debug) Console.WriteLine("** Stopping nethub interface...");
Same as above.

2020-12-22 05:09 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        	Int32 b2 = this.getByte(str) & 0xFF;
Prefer "int" rather than "Int32"

2020-12-22 05:10 UTC, livingcomputermuseum commented on D/Program.cs
> +                            doStart = true;
Can you just set Configuration.Start directly here and eliminate doStart?

2020-12-22 05:11 UTC, livingcomputermuseum commented on D/UI/ConfigurationDialog.cs
> +            EthernetInterfaceListBox.Enabled = true; // Configuration.HostRawEthernetInterfacesAvailable;
Just remove this line entirely.

2020-12-22 05:12 UTC, livingcomputermuseum commented on D/UI/ConfigurationDialog.cs
> +                MessageBox.Show("The NetHub host can not be empty");
"cannot"

2020-12-22 05:13 UTC, livingcomputermuseum commented on D/UI/DWindow.cs
> +		}
Fix tabs.

2020-12-22 05:14 UTC, livingcomputermuseum commented on D/UI/DWindow.cs
> +        	_system.IOP.MiscIO.AltBoot = Configuration.AltBootMode;
Fix tabs.

2020-12-22 05:15 UTC, livingcomputermuseum commented on D/readme.txt
> +connection to the Dodo NetHub can be configured instead of using a real network.
Suggest adding a section somewhere covering Dodo (what it is, where to get it, etc...)

2020-12-22 05:17 UTC, livingcomputermuseum commented on D/Darkstar.csproj
> +  </PropertyGroup>
Actually, are any of these changes necessary?

2020-12-22 05:18 UTC, livingcomputermuseum commented on D/Ethernet/EthernetController.cs
> +            		Console.WriteLine("** connected to nethub");
Would prefer not to have WriteLines in the code (use Log.Write where applicable.)  See other instances in this and other files as well.

2020-12-22 05:19 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +		private Byte[] sendBuffer = new byte[1026]; // this assumes that there is only ONE processing thread (which is the case for DarkStar!)
Member variables should be prefixed with an underscore.

2020-12-22 05:20 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        	this.receiverThread.Start();
No need for "this"

2020-12-22 05:20 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        private void stopReceiverThread() {
PascalCase please

2020-12-22 05:21 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        private ulong readAddress(byte[] data, int at) {
PascalCase

2020-12-22 05:21 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        private byte getByte(NetworkStream str) {
PascalCase

2020-12-22 05:21 UTC, livingcomputermuseum commented on D/Ethernet/NethubInterface.cs
> +        private int getLenPrefix(NetworkStream str) {
PascalCase

2020-12-22 05:23 UTC, livingcomputermuseum requested changes
See the comments in the code (mostly nitpicky, sorry).  Thanks for submitting this!

2020-12-22 22:49 UTC, devhawala commented
Hello,

no problem with pedantic code-reviews :-)

The changes in the new commit should incorporate your comments, hoping not to have overseen something.

For the 2 additional words for incoming packets, i removed the change in Darkstar, relying on the configuration option `ether.useDarkstarWorkaround` in Dodo until the real reason for the lost packet problem is found and fixed. Having thought about it, Dodo may have the issue.

Greetings, Hans

2020-12-25 07:46 UTC, livingcomputermuseum approved these changes
Looks good, thanks!

2020-12-25 07:47 UTC, merged